site_name: PSRule for Cloud Adoption Framework
site_url: https://microsoft.github.io/PSRule.Rules.CAF
site_description: A suite of rules to testing Azure resources against the Cloud Adoption Framework (CAF) using PSRule.
site_author: Microsoft

repo_url: https://github.com/microsoft/PSRule.Rules.CAF
edit_uri: blob/main/docs/

extra_css:
- assets/stylesheets/extra.css

theme:
  language: en
  name: material
  custom_dir: overrides
  font:
    text: Roboto
  palette:
    primary: black
    accent: blue
  logo: assets/ms_icon.png
  favicon: assets/ms_icon.png
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.instant
  - navigation.indexes
  - navigation.sections:
      level: 1
  - navigation.tabs
  - content.code.annotate

nav:
  - Home: index.md
  - Getting started:
    - Overview:
      - About: about.md
      - Features: features.md
      - FAQ: faq.md
    - Installation: install-instructions.md
    - Quickstarts:
      - Create a standalone rule: quickstart/standalone-rule.md
    - Testing infrastructure code:
      - Expanding source files: expanding-source-files.md
      - Using templates: using-templates.md
      - Using Bicep source: using-bicep.md
      - Creating your pipeline: creating-your-pipeline.md
      - Working with baselines: working-with-baselines.md
    - Testing deployed resources:
      - Exporting rule data: export-rule-data.md
      - Analyzing resources: analyzing-resources.md
    # - Authoring rules:
    #   - Testing infrastructure: authoring/testing-infrastructure.md
    #   - Using expressions: authoring/using-expressions.md
    #   - Storing and naming rules: authoring/storing-rules.md
    #   - Packaging rules in a module: authoring/packaging-rules.md
    #   - Writing rule help: authoring/writing-rule-help.md
    # - Running rules:
    #   - Creating your pipeline: creating-your-pipeline.md
    #   - Validating locally: validating-locally.md
    #   - Analysis output: analysis-output.md
    # - Tutorials:
    #   - Validate Azure resource configuration: scenarios/azure-resources/azure-resources.md
    #   - Azure resource tagging example: scenarios/azure-tags/azure-tags.md
    #   - Kubernetes resource validation example: scenarios/kubernetes-resources/kubernetes-resources.md
    # - Concepts:
    #   - Using within continuous integration: scenarios/validation-pipeline/validation-pipeline.md
    # - Troubleshooting: troubleshooting.md
    - License and contributing: license-contributing.md
    - Related projects: related-projects.md
    - Releases:
      - Change log:
        - v0: 'CHANGELOG-v0.md'
      # - Upgrade notes: upgrade-notes.md
      # - Deprecations: deprecations.md
    - Support: support.md
  - Setup:
    - Configuring options: setup/configuring-options.md
    - Configuring rule defaults: setup/configuring-rules.md
    - Configuring expansion: setup/configuring-expansion.md
  - Reference:
    - Commands:
      - Assert-PSRule: commands/PSRule/en-US/Assert-PSRule.md
      - Export-PSRuleBaseline: commands/PSRule/en-US/Export-PSRuleBaseline.md
      - Get-PSRule: commands/PSRule/en-US/Get-PSRule.md
      - Get-PSRuleBaseline: commands/PSRule/en-US/Get-PSRuleBaseline.md
      - Get-PSRuleHelp: commands/PSRule/en-US/Get-PSRuleHelp.md
      - Get-PSRuleTarget: commands/PSRule/en-US/Get-PSRuleTarget.md
      - Invoke-PSRule: commands/PSRule/en-US/Invoke-PSRule.md
      - New-PSRuleOption: commands/PSRule/en-US/New-PSRuleOption.md
      - Set-PSRuleOption: commands/PSRule/en-US/Set-PSRuleOption.md
      - Test-PSRuleTarget: commands/PSRule/en-US/Test-PSRuleTarget.md
    - Assertion methods: concepts/PSRule/en-US/about_PSRule_Assert.md
    - Baselines: concepts/PSRule/en-US/about_PSRule_Baseline.md
    - Badges: concepts/PSRule/en-US/about_PSRule_Badges.md
    - Conventions: concepts/PSRule/en-US/about_PSRule_Conventions.md
    - Documentation: concepts/PSRule/en-US/about_PSRule_Docs.md
    - Expressions: concepts/PSRule/en-US/about_PSRule_Expressions.md
    - Keywords: keywords/PSRule/en-US/about_PSRule_Keywords.md
    - Options: concepts/PSRule/en-US/about_PSRule_Options.md
    - Rules: concepts/PSRule/en-US/about_PSRule_Rules.md
    - Selectors: concepts/PSRule/en-US/about_PSRule_Selectors.md
    - Suppression Groups: concepts/PSRule/en-US/about_PSRule_SuppressionGroups.md
    - Variables: concepts/PSRule/en-US/about_PSRule_Variables.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.snippets
  - pymdownx.highlight:
      auto_title: false
      anchor_linenums: false
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - mdx_truly_sane_lists
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: '#'
      separator: '-'

plugins:
- mkdocs-simple-hooks:
    hooks:
      on_page_markdown: "docs.hooks:replace_maml"
      # on_nav: "docs.hooks:build_reference_nav"
- search
- git-revision-date

extra:
  version:
    provider: mike
    default: stable

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/microsoft/PSRule.Rules.CAF/

  local:
    social_preview: https://repository-images.githubusercontent.com/228310554/f6ce44e6-8f1a-4953-9f59-4a7ed65c5fb6
    repo_issue: https://github.com/microsoft/PSRule.Rules.CAF/issues
    repo_discussion: https://github.com/microsoft/PSRule.Rules.CAF/discussions

  # alternate:

  #   # Switch to English
  #   - name: English
  #     link: /en/
  #     lang: en
